services:
  - type: web
    name: movies-et-moi
    env: docker
    plan: free
    region: frankfurt  # ou choisissez la région la plus proche de vos utilisateurs
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod 